version: "3.9"
services:

  mysql:
    image: mysql
    container_name: MySQL_Database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306

  ubuntu:
    build: .
    container_name: Django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/django
    ports:
      - 9000:8000
    depends_on:
      - mysql

  web:
    image: nginx
    container_name: Web_Server
    volumes:
     - ./nginx:/etc/nginx/
    ports:
     - 80:8080
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

#notes
  #volumes:
  #  database:
  #  django:

  #version: "3.9"
  #service:
  #
  #  service-1:
  #  image:
  #  ports:
  #  -  8080:8080
  #  networks:
  #  -  frontend
  #  volumes:
  #  -
  #  environment:
  #  -
  #
  #  service-2:
  #  image:
  #  ports:
  #  -  8080:8080
  #  networks:
  #  -
  #  volumes:
  #  -
  #  environment:
  #  -
  #
  #networks:
  #  e.g.frontend:
  #volumes:
  #  e.g.database:
