version: "3.9"
services:

  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306

  ubuntu:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
      - ./docker:/django
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  web:
    image: nginx
    volumes:
     - ./:/etc/nginx/templates
#     - ./nginx:/etc/nginx/templates
#     - .nginx/:/etc/nginx/templates
#     - /etc/nginx/templates:./
    ports:
     - "82:8080"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

#notes
  #volumes:
  #  database:
  #  django:

  #version: "3.9"
  #service:
  #
  #  service-1:
  #  image:
  #  ports:
  #  -  8080:8080
  #  networks:
  #  -  frontend
  #  volumes:
  #  -
  #  environment:
  #  -
  #
  #  service-2:
  #  image:
  #  ports:
  #  -  8080:8080
  #  networks:
  #  -
  #  volumes:
  #  -
  #  environment:
  #  -
  #
  #networks:
  #  e.g.frontend:
  #volumes:
  #  e.g.database:
